language: python
python:
  - "3.8"

before_install:
  - python -m pip install --upgrade setuptools pip virtualenv

# command to install dependencies
install:
  - pip install -e .
  - pip install pytest

# command to run tests
script: py.test
